### ISSUE TITLE
Include IATA "city" location codes

### ISSUE THREAD

**Issue by etiennecrb** [mborsetti/airportsdata#19]
Hello,

Very nice project, one with the most up to date data, thank you.

However, IATA location codes representing a city are missing: for instance PAR for Paris, LON for London etc. I don't know from where exactly the data comes from, but including those location codes in the dataset would be a great feature, how can I help you with that?

**Comment by mborsetti** [comment]
> Very nice project, one with the most up to date data, thank you.

Thanks!

> However, IATA location codes representing a city are missing: for instance PAR for Paris, LON for London etc. I don't know from where exactly the data comes from, but including those location codes in the dataset would be a great feature, how can I help you with that?

Right now IATA's Multi Airport Cities list is in the project's readme sub-file https://github.com/mborsetti/airportsdata/blob/main/README_IATA.rst.  How do you propose City Codes should be incorporated?  What use cases do you envision?

**Comment by etiennecrb** [comment]
> Thanks for the suggestion. Right now IATA's Multi Airport Cities list with the City Codes is in the project's readme sub-file https://github.com/mborsetti/airportsdata/blob/main/README_IATA.rst.

Sorry, I should have read the README more carefully :see_no_evil: .

> How do you propose City Codes should be incorporated? What use cases do you envision?

The use case I envision is to be able to suggest a "All airports" choice as you can see on some airlines search engine:

![20221209_105056](https://user-images.githubusercontent.com/12871063/206674646-f366a325-4fef-4f45-b202-53113c556f90.png)

However I am a bit surprised, I thought city codes where unique and distinct from airport codes but it's not the case (BRU, DXB...) so I am not sure about the implementation... At least the data is available in this repo, so let me close this issue for now except if on your side you have a clear idea of what should be done.

**Comment by etiennecrb** [comment]
However the list seems incomplete, for instance [BER](https://www.iata.org/en/publications/directories/code-search/?airport.search=BER) is missing.

**Comment by DravenJohnson** [comment]
It's a nice project, thank you

But yes, missing city code would be something. I believe the usecase is like etiennecrb suggested, search "All airports"

from the README_IATA.rst file, it looks like NYC (for New York) is there but dig into the database, if I do:
```
>>> iata = airportsdata.load('IATA')
>>> iata['NYC']
```

It will throw KeyError.

Not sure about other location but NYC definetily will be a useful information when you try to search both JFK and LGA and even include EWR.

**Comment by mborsetti** [comment]
> It's a nice project, thank you
@DravenJohnson Thanks!

> But yes, missing city code would be something. I believe the usecase is like etiennecrb suggested, search "All airports" from the README_IATA.rst file, it looks like NYC (for New York) is there but dig into the database, if I do:
> 
> ```
> >>> iata = airportsdata.load('IATA')
> >>> iata['NYC']
> ```
> 
> It will throw KeyError.

I am sorry if the README_IATA.rst, which is provided as an information aid, does not repeat the scope of the project from README.rst, but it's a "database of location and timezone data for nearly every **operational airport and landing strip in the world**, and NYC is neither.

> Not sure about other location but NYC definetily will be a useful information when you try to search both JFK and LGA and even include EWR.

This project is open source, so you're welcome to contribute code that builds on top of it, and **it will be welcomed**. But you will have to architect this new code to handle exactly this type of situations, where the airports that comprise a group called "NYC" by IATA are spread across geography and even state lines (EWR is in New Jersey, JFK and LGA in New York state).

**Comment by mborsetti** [comment]
Please see release 20230528 and [README_IATA.rst](https://github.com/mborsetti/airportsdata/blob/main/README_IATA.rst) for the new support of IATA Multi Airport City Location Codes.
