### ISSUE TITLE
City name for IATA code FRA

### ISSUE THREAD

**Issue by deezknuts** [mborsetti/airportsdata#20]
Currenty city name for IATA  FRA code returns "Frankfurt-am-Main".  When interacting w/ Maxmind, a company that provide GEOIP databases,  their systems will only recognize, "Frankfurt am Main".    Can FRA city name be updated without the hyphens in the name?

**Comment by mborsetti** [comment]
Thanks for the report; the hyphenation is indeed incorrect.  Fixed and new release on its way.
