### ISSUE TITLE
Some Airports Missing (and Runways Number)

### ISSUE THREAD

**Issue by Artorias93** [mborsetti/airportsdata#22]
Hi Dude, amazing library!
I saw that in the original list of airports there are some that are missing in your package, such as KXTA.
Is there any possibility to update the list of airports?

Also, is it possible to have a column indicating the number of Runways present at each airport?

Thank you very much for your contribution!

**Comment by mborsetti** [comment]
Ciao Artorias,

Grazie!

I will answer in English.

KXTA is not an active airport per FAA: https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dafd/search/advanced/

As to runway data, I have no access to that information, but if you want to contribute it it will be gladly accepted!

**Comment by Artorias93** [comment]
Non sapevo fossi italiano, possiamo tranquillamente parlare la nostra lingua! :)

Quindi il tuo pacchetto tratta solo aeroporti attivi? C'è un modo per ottenere anche tutti quelli presenti nel GitHub da cui stai forkando, a prescindere dallo stato di attività?

Per le runways... In realtà sto cercando una buona fonte anche io che possa fornire quel dato, ma non ne trovo una come si deve :'(
