### ISSUE TITLE
HSSS -> HSSK

### ISSUE THREAD

**Issue by jonaseberle** [mborsetti/airportsdata#25]
Hi and thanks for this great source!

According to this Jeppessen circular https://ww2.jeppesen.com/wp-content/uploads/2021/02/HSSS_HSSK_2102_AMM_ALERT.pdf (and quoted on [Wikipedia](https://en.wikipedia.org/wiki/Khartoum_International_Airport))
Khartoum International HSSS has changed its ICAO code to HSSK in AIRAC 2102.

**Comment by mborsetti** [comment]
Thanks!  Didn't see this before today's release, will make the next one.

**Comment by jonaseberle** [comment]
Thank you!

**Comment by mborsetti** [comment]
Fix released in 20230716.  Thanks for the report!
