### ISSUE TITLE
New Brașov-Ghimbav Intl. LRBV

### ISSUE THREAD

**Issue by jonaseberle** [mborsetti/airportsdata#28]
LRBV is completely new and had its first scheduled flights this June.

There has been some confusion with the ICAO code (some databases have it as the old nearby small airfield LRBG), but now the Romanian AIP has definitive answers.

https://www.aisro.ro/,
(Publications -> AIP -> AD2.29)
LRBV Administrative data https://www.aisro.ro/aip/2023-07-13/DOCS/AIP/AD/AD2/AD_2_29_LRBV/LR_AD_2_LRBV_en.pdf

IATA code "GHV": https://www.iata.org/en/publications/directories/code-search/?airport.search=GHV

**Comment by mborsetti** [comment]
Hello Jonas,

Thank you very much for a super well-researched contribution, very much appreciated.  Added to v20230717, just released.
