### ISSUE TITLE
New airport: PUW

### ISSUE THREAD

**Issue by YPCrumble** [mborsetti/airportsdata#3]
Hi - thanks for maintaining this repo! I've used the prior fork quite a lot and frequently have changes required by users of my website. Is the goal of this repo to be more actively maintained?

One missing airport I've found is PUW - see https://en.wikipedia.org/wiki/Pullman%E2%80%93Moscow_Regional_Airport

I could make a PR next week sometime if helpful!

**Comment by mborsetti** [comment]
> I could make a PR next week sometime if helpful!
Yes, PRs would be **extremely** helpful, thanks!

**Comment by Spencer-Yoder** [comment]
Looks like it was already added at some point. Line 14,271

`"KPUW","PUW","Pullman Moscow Regional Airport","Pullman/Moscow","Washington","US",2556,46.7439002991,-117.1100006104,"America/Los_Angeles"`

**Comment by mborsetti** [comment]
Thanks!  It must have been programmatically added (did some cleanup for US airports)
