### ISSUE TITLE
Unable to find few airports - ZVJ, QUK, ZBL, WSI

### ISSUE THREAD

**Issue by BhagyalakshmiMurugesan** [mborsetti/airportsdata#33]
Hi Team,

Good Day!

If possible, could you please ensure all the airports code have been added to the library? I could see few of the airports are missing now.

Thank you,

**Comment by mborsetti** [comment]
Hello @BhagyalakshmiMurugesan,

This library is built and maintained by the contributions of our amazing community. We rely on valuable contributions to continuously improve the accuracy and comprehensiveness of the library.  

Therefore, we would be extremely grateful if you could consider sharing the data for the airports you mentioned. Your contribution would be invaluable in expanding the library's reach and benefitting all of its users.

Thank you for your time and consideration.

**Comment by mborsetti** [comment]
Hello @BhagyalakshmiMurugesan,

Thank you for your interest.

ZVJ, QUK, WSI are not IATA codes per https://www.iata.org/en/publications/directories/code-search/ and are therefore not valid/eligible for inclusion in this database.

ZBL seems to be assigned to the city of Biloela in Queensland, AU, but this city is served only by the YTNG/THG Thangool Airport. Please contribute your knowledge of this code.

Thanks!
