### ISSUE TITLE
Please add Ezhou Airport

### ISSUE THREAD

**Issue by HaGoijer** [mborsetti/airportsdata#34]
Please add Ezhou Airport

"icao","iata","name","city","subd","country","elevation","lat","lon","tz","lid"
"ZHEC","EHU","Ezhou Huahu Airport","Ezhou","Hubei","CN",30.342856, 115.029611,"Asia/Shanghai",""

See:

- https://en.wikipedia.org/wiki/Ezhou_Huahu_Airport
- https://www.iata.org/en/publications/directories/code-search/?airport.search=EHU

**Comment by mborsetti** [comment]
Thanks for the contribution!
