### ISSUE TITLE
Add BKPR and OPRN

### ISSUE THREAD

**Issue by niclaswue** [mborsetti/airportsdata#36]
Please add these airports:

"OPRN","ISB","Benazir Bhutto International Airport","Islamabad","Punjab","PK",1667,33.616388888889,73.099166666667,"Asia/Karachi",""

"BKPR","PRN","Pristina International Airport","Pristina","","XK",1788,42.572777777778,21.035833333333,"Europe/Belgrade",""

**Comment by mborsetti** [comment]
Thanks!

BKPR/PRN is an appreciated contribution and will be included in the next release.

OPRN is closed (replaced by OPIS/ISB, already in the database).

**Comment by niclaswue** [comment]
Great, thank you!
