### ISSUE TITLE
Please add these airports:

### ISSUE THREAD

**Issue by 1oKPro1** [mborsetti/airportsdata#37]
"","OMN","Zomin","Zomin","Djizak","UZ",,40.015356,68.413948,"Asia/Tashkent",""

**Comment by 1oKPro1** [comment]
"","MOK","Muynaq","Muynaq","Karakalpakstan","UZ",177,43.7551994324,59.0308990479,"Asia/Samarkand",""

**Comment by mborsetti** [comment]
Thanks!  Will be processed next weekend.

**Comment by 1oKPro1** [comment]
Good day Mike. My name is Abboshon. I myself work in the field of aviation
and tourism, and international programming. If there are errors or new
airport and city codes, they can only be added through a message and
through you. Or is there some other way?

пн, 18 мар. 2024 г. в 15:28, Mike Borsetti ***@***.***>:

**Comment by mborsetti** [comment]
@1oKPro1 apologies -- this slipped through the cracks.  

OMN is no longer a IATA code and satellite shows a very abandoned former strip so it won't be added; MOK was indeed missing from the existing entry, and it has been added to the next release.

As per the method of contribution, feel free to open an issue or to read up on how to contribute via GitHub; there are plenty of tutorials out there!
