### ISSUE TITLE
ADD LTCV, UTFF, LTCU, DTNH, OKBK, ESKS

### ISSUE THREAD

**Issue by niclaswue** [mborsetti/airportsdata#40]
Hi there,

the following airports are missing:

- LTCV
- UTFF
- LTCU
- DTNH
- OKBK
- ESKS

I created the entries using a language model, so please double check the values.

**LTCV**
https://en.wikipedia.org/wiki/%C5%9E%C4%B1rnak_%C5%9Eerafettin_El%C3%A7i_Airport
```
"LTCV","NKT","Şırnak Şerafettin Elçi Airport","Cizre","Şırnak","TR",621,37.36389,42.06000,"Europe/Istanbul","LTCV"
```
**UTFF**
https://en.wikipedia.org/wiki/Fergana_International_Airport
```
"UTFF","FEG","","Fergana","Fergana Region","Uzbekistan",625,40.35889,71.74417,"Asia/Tashkent","UTFF"
```

**LTCU**
https://en.wikipedia.org/wiki/Bing%C3%B6l_Airport
```
"LTCU", "BGG", "Bingöl Airport", "Çeltiksuyu", "Turkey", "TR", 1063, 38.86111, 40.59250, "Europe/Istanbul", "LTCU"
```

**DTNH**
https://en.wikipedia.org/wiki/Enfidha–Hammamet_International_Airport
```
"DTNH","NBE","","Enfidha International Airport","Tunisia","TN",0,36.07217,10.43861,"Africa/Tunis","DTNH" 

Note: The elevation field was left blank as it was not specified in the Wikipedia article. 
```

**OKBK**
https://en.wikipedia.org/wiki/Kuwait_International_Airport
```
"KWI","KWI","","Kuwait International Airport","Farwaniya Governorate","KWT",63,"29.223333","47.979722","Asia/Kuwait","KWI"
```

**ESKS**
https://en.wikipedia.org/wiki/S%C3%A4len/Scandinavian_Mountains_Airport
```
"ESKS","SCR","Sälen/Scandinavian Mountains Airport","Rörbäcksnäs","Dalarna","SE",490,61.1590,12.8400,"Europe/Stockholm","ESKS"
```

**Comment by mborsetti** [comment]
Thank you for the great contribution.  I've validated them all (and fixed things such as elevation, which for historical reasons is in feet and not metres) and they will be in the next release, with the exception of OKBK, which has been replaced by OKKK as per linked article in Wikipedia, and who is already in the database.
