### ISSUE TITLE
Metropolitan area airport codes

### ISSUE THREAD

**Issue by jonkaumheimer** [mborsetti/airportsdata#42]
Hi,

Would it be possible to include metropolitan area airport codes?

Examples:
NYC representing the New York City area
STO represeing Stockholm area

https://en.wikipedia.org/wiki/IATA_airport_code#Cities_with_multiple_commercial_airports
https://en.wikivoyage.org/wiki/Metropolitan_area_airport_codes
https://www.iata.org/en/publications/directories/code-search/?airport.search=nyc
https://www.iata.org/en/publications/directories/code-search/?airport.search=sto

Regards,
Jon

**Comment by mborsetti** [comment]
Hi Jon,

IATA Multi Airport Cities are in a separate file, as per the main [README](https://github.com/mborsetti/airportsdata/blob/main/README.rst) (which points [here](https://github.com/mborsetti/airportsdata/blob/main/README_IATA.rst) for more details). 

As they are not airports, they require a different data structure and therefore in Python they are retrievable through a separate API.

I guess the main API could be extended to include them; what is your use case?

**Comment by jonkaumheimer** [comment]
Hi, thank you, and sorry, I should have read the readme file.

Br,
Jon
