### ISSUE TITLE
Interesting idea - programmatically sync data with wikipedia

### ISSUE THREAD

**Issue by YPCrumble** [mborsetti/airportsdata#5]
It might be nice to pull Wikipedia's list of airports and sync that with this repo using a GitHub action.

Ideally using SPARQL or the MediaWiki API - `wikipedia` Python module. I don't have experience with the API but SPARQL seems like a pretty good way to get large structured data dumps from Wikipedia.

**Comment by mborsetti** [comment]
Oh, that's quite intriguing. I am not familiar with either, but I like the approach and while I currently don't have time I'll definitely look into it in the future (or collaborate with you if you do have time).

Many thanks!

**Comment by mborsetti** [comment]
After gaining a bit of experience on the quality of data for some less-known airports on Wikipedia, I am going to close this as I feel that some type of data checking is required.
